### PR TITLE
Move snap to build-aux

### PR DESCRIPTION
**Pull request by hellsworth**
Changes proposed in this pull request:
- moves build/snap to build-aux/snap so snapcraft can find it

### CODE REVIEW

**Comment by TrechNex** [comment]
@bochecha I've already suggested that should probably be created as an issue because it might have side-effects. I believe @hellsworth has already done so.

**Comment by hellsworth** [comment]
> Should we just rename the whole build folder to build-aux/?
@bochecha I've opened [an issue to track what happens with build/](https://github.com/glimpse-editor/Glimpse/issues/233).

> You probably don't want to commit the Vim file (*.swp).
You're right but I dont' see the .swp file in the list of changed files... it's not listed in the commit info either so correct me if i'm wrong, but I don't think the .snapcraft.swp file is committed.

> Also, it would be nice to explain in the commit message why this is needed.
Good suggestion. I've added a bit to the commit message. Please let me know if this is sufficient.

**Comment by BrainBlasted** [comment]
> Should we just rename the whole `build` folder to `build-aux/`?
> 
> You probably don't want to commit the Vim file (`*.swp`).
> 
> Also, it would be nice to explain in the commit message **why** this is needed. Otherwise we might forget and in a year someone decides "build-aux" isn't a nice name, renames it, breaks the snap build again. confused

This could introduce some weirdness when rebasing, which is why I'm hesitant to rename the whole folder. If it would be fine, I think that would be a good move.

**Comment by bochecha** [comment]
> > You probably don't want to commit the Vim file (*.swp).
> You're right but I dont' see the .swp file in the list of changed files... it's not listed in the commit info either so correct me if i'm wrong, but I don't think the .snapcraft.swp file is committed.

Screenshot from 2019-11-22 22-42-41

Git is hiding it from you for some reason.

**Comment by hellsworth** [comment]
ok swp file removed. Thanks for pointing it out @bochecha .

**Pull request merged**
