### PR TITLE
Reinstated Symbolic icons and Dark/Light themes

### PR DESCRIPTION
**Pull request by TrechNex**
Sets Light theme with Symbolic-Inverted icons as the default (upstream does the opposite).

"Gray" UI theme and "Color" icons have been omitted based on feedback from Matrix.

### CODE REVIEW

**Comment by BrainBlasted** [comment]
I think it would be better to keep the grey UI theme, but not as default. See the "Dark Mode" questions of the elementary OS [user interface study](https://blog.elementary.io/user-interface-study-findings/).

**Comment by BrainBlasted** [comment]
Actually, I'm mistaken - the Grey and Dark themes are separate, and the Grey theme seems okay to remove.

**Comment by TrechNex** [comment]
Apologies, that's my fault.
I reinstated the "Dark" and "Light" UI themes, and also brought back the "Symbolic" and "Symbolic-Inverted" icons.

**Comment by TrechNex** [comment]
Switched back to Dark theme with symbolic icons to follow upstream conventions and the examples I saw on https://wiki.getglimpse.app

**Comment by TrechNex** [comment]
Confirming that I intend to squash and merge into a single commit when PR is approved

**Pull request merged**
