### PR TITLE
Accessibility improvements

### LINKED ISSUE #450: Is the current UI font accessible enough?
A complaint I hear frequently is that the default font size in recent versions of the GNU Image Manipulation Program is too small. There is no straightforward way to fix that through the interface, and it has to be changed manually in `gtkrc`.
(Source: https://www.gimpusers.com/forums/gimp-user/21830-can-t-read-small-ui-text-on-gimp-2-10-18)

The font choice is also an interesting one. In principle "Monaco" isn't bad, but there are fonts that are recommended to help dyslexic people. Perhaps "Open Sans" would be a better choice? https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide

### PR DESCRIPTION
**Pull request by TrechNex**
Fixes #450.

Changes proposed in this pull request:
- Increases default size of icons so they're not tiny on modern displays of 720p or higher
- Increases default size of layer previews and undo history
- Provide option to increase font size in Themes preferences window (TODO)

I am still evaluating if "Sans" is the most accessible font choice we can go with. I've stuck with it for now for compatibility.

### CODE REVIEW

**Comment by TrechNex** [comment]
I should mention that we have already set the High Contrast icon pack as the default for accessibility too.

Something I would be intrigued to hear feedback on is whether we should switch to using the Light theme instead of Dark as the default. This tends to get people a bit hot under the collar as people like the aesthetics of dark and believe it reduces eye strain, while others find it difficult to work with and have to change it each time.

**Comment by TrechNex** [comment]
Preview of changes on a 1080p screen in Windows 10 Pro

image

**Comment by jannuary** [comment]
Would 14pt be usable on lower res screens? Perhaps there should be an option to opt out from using large fonts and icons in the settings.

As for font choice, perhaps [Inter](https://rsms.me/inter/) (licensed under SIL Open Font License 1.1) could work? 
Screenshot from 2020-11-09 11-12-42

Also, could [OpenDyslexic](https://www.opendyslexic.org/) (also SIL-OFL) be available as an option in settings? 
Screenshot from 2020-11-09 11-16-36 
It's specifically designed to be readable for people with dyslexia, and I personally know people this font helps a lot.

**Comment by TrechNex** [comment]
@jannuary thank you for those font suggestions! I will experiment with those and verify the licensing is compatible with GPLv3. (I don't see any reason why it wouldn't be, but always worth double-checking)

As for the font size, we're stuck between a rock and a hard place on that. There is no way to fix it through the UI, so changing it does require the user to edit configuration files, and not everyone has the technical skill to do that. I am hoping to find it can be overriden globally in the `gtkrc` file, as that would at least save people having to edit theme files like I have here.

I think we should probably test screen resolutions from 720p or above, as that seems to be the most common configuration for daily workhouse machines in 2020: https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide

We have a similar issue with the icon sizes. The algorithm for "guessing" how big they should be is tailored specifically for much lower resolutions, but is really bad (imho) on high DPI displays because of a known limitation with GTK2. 

That means partially sighted people have to navigate through using tiny icons and text to change it in Edit > Preferences > Interface > Themes, assuming they even know that is the place to fix it in the first place.

I think it makes more sense for us to pick out the resolutions we're supporting and try to base the result on that.

My initial tests were on 1080p screens, so I will test at a wider range of resolutions before merging these changes in. :)

**Comment by jannuary** [comment]
I suppose it's true that GTK 2 and GNU IMP is really inflexible in terms of UI, though if font/icon size is set by the theme, isn't it trivial to just add another theme with large fonts/icons, and the set that as the default?
image

**Comment by TrechNex** [comment]
Yes, that's a much better idea! It gives people the option to revert back easily if they don't like it.

Thank you for that suggestion @jannuary

**Comment by TrechNex** [comment]
Only thing I would say (thinking about it) is I'll probably call the themes "Glimpse Dark" and "Glimpse Light".

If I call them "Dark (Accessible)" or "Light (Accessible)" then we potentially run the risk of certain GNU I.M.P devs yelling at us for suggesting their existing themes aren't accessible and demanding evidence to prove our assertion. 😂

**Comment by TrechNex** [comment]
Closing as this was superceded by #502

**Pull request closed without merging**
