### PR TITLE
Remapped keyboard shortcuts for saving and exporting

### LINKED ISSUE #394: Unite the "export" and "file save"
### Is your feature request related to a problem? Please describe
The upstream splitted the "file save" command in "export" and "file save" a few years ago. The reason is, "exports"-formats (jpeg, tif, png, gif, bmp, ...) don't save the done editions. 
But saving with "Export" is very confusing for most user. Ctrl-S doesn't works like expected. etc.

### Describe the solution you'd like
More handy way could be solution where you save always the original file (jpeg, tif, png, gif, bmp, ...) and a checkmark (named "save current project") where you can choose to save the xcf-file  or not. Often it isn't needed. 
Once saved as a project, each ctrl-s saves both, original file (jpeg, tif, png, gif, bmp, ...) and xcf-file.

### Describe alternatives you've considered
Unite the "export" and "file save". Add a text to the file dialogue how warns the user, if the editing isn't saved.

### PR DESCRIPTION
**Pull request by TrechNex**
Fixes #394

Changes proposed in this pull request:
- Remaps Ctrl+S to File > Export as...
- Remaps Ctrl+Shift+S to File > Save (or File > Save as... if new)
- Preserves the existing mapping for Ctrl+E (File > Export)

I believe this addresses the user complaint that Ctrl+S does not necessarily behave the way you would expect it to, and power users still have the option to use Ctrl+Shift+S to continue using the old behaviour.

### CODE REVIEW

**Comment by TrechNex** [comment]
Early feedback I'm getting on social media currently is overwhelmingly negative to this idea, so this change could well be dropped 😂

**Comment by TrechNex** [comment]
Closing because of overwhelming negative feedback. That was quick!

**Comment by lf-** [comment]
I'm not really a fan of this since I usually make new things that are fairly technically involved in glimpse and its predecessor, so the primary file format I want is actually xcf. It feels like this UI change deemphasizes the use of project files, which might make sense for the quick editing case but not as much the multiple layers, paths, etc kind of use case I'm used to. 

How does Adobe handle this? Just curious. 

:)

**Comment by TrechNex** [comment]
Adobe Photoshop I believe splits out File > Save and File > Export. However, if we're pitching to casual users running programs like Paint.NET, it potentially makes a bit more sense to merge the two into a common File > Save like earlier versions of the GNU Image Manipulation Program did.

I appreciate however that power users probably hate this idea too, so it's something we need to keep taking feedback from our user base about. One potential idea is making Ctrl+S pop up the correct dialogue depending on the file type you actually have open, but there could be some limitations to that approach too.

**Pull request closed without merging**
