### PR TITLE
[snap] Many ported updates from the snapcrafters/gimp project

### PR DESCRIPTION
**Pull request by hellsworth**
Changes proposed in this pull request:
  - Update the cflags from O2 to O3
  - Update build and runtime libraries
  - Include launcher-specific directly
  - Better organized ldcache actions

### CODE REVIEW

**Comment by hellsworth** [comment]
This is the original commit (made relative to beta-g210) that I then cherry-pick'd it onto the [glimpse-0-2](https://github.com/glimpse-editor/Glimpse/pull/533) and [dev-g210](https://github.com/glimpse-editor/Glimpse/pull/534) updates branches.

**Comment by hellsworth** [comment]
I built this locally, and then tested it in a hirsute ubuntu vm and it all looked great.

**Comment by hellsworth** [comment]
I built this locally, and then lightly tested it in a hirsute ubuntu vm and it all looked great.

**Comment by LunaTheFoxgirl** [comment]
Closing this as it seems to be the same as the other snap pr

**Comment by hellsworth** [comment]
For the three branches, dev-g210, beta-g210, and glimpse-0-2, the snapcraft.yaml is slightly different to track the different branches and such. This was how Bobby wanted it way back... So that is why there are 3 PRs.

If you would like to only keep one branch updated/published, that's fine but just tell me what you'd like to do.

**Comment by hellsworth** [comment]
Here is where you can see the 3 different glimpse snaps on launchpad: https://code.launchpad.net/~hellsworth/desktop/+git/glimpse-editor/+snaps

* glimpse-editor-stable tracks glimpse-0-2 and gets published to stable (the snap store "stable" channel)
* glimpse-editor-beta tracks beta-g210 and gets published to beta
* glimpse-editor tracks dev-g210 and gets published to edge

**Pull request merged**
