### PR TITLE
[snap] Many ported updates from the snapcrafters/gimp project

### PR DESCRIPTION
**Pull request by hellsworth**
Changes proposed in this pull request:
  - Update the cflags from O2 to O3
  - Update build and runtime libraries
  - Include launcher-specific directly
  - Better organized ldcache actions

### CODE REVIEW

**Comment by hellsworth** [comment]
I built this locally, and then lightly tested it in a hirsute ubuntu vm and it all looked great.

**Comment by hellsworth** [comment]
Are the windows builds known issues or did I actually mess something up for windows?

**Comment by TrechNex** [comment]
cc @LunaTheFoxgirl @BrainBlasted 

@hellsworth in case you missed the news as it's been a while since we chatted on Matrix, I ended my involvement with the project in Feb 2021 at the request of my employer. The broken Windows build was a known issue at that time.

**Comment by hellsworth** [comment]
Thanks @TrechNex , I knew that you had ended your involvement but did not know the windows broken build was a known issue. Since it's a known problem and these changes *do* fix the linux build, @LunaTheFoxgirl and @BrainBlasted would you consider merging this?

**Comment by LunaTheFoxgirl** [comment]
This PR works on Linux but Windows build still needs to be fixed, I'll go ahead and check + merge it now

**Comment by LunaTheFoxgirl** [comment]
LGTM, I've merged it. When I get time I'll look in to the broken Windows build + a bug with the installer.

**Pull request merged**
