### PR TITLE
Translates Gimpressionist menu item, window title and default text

### LINKED ISSUE #267: Missed a plugin rename
image

### PR DESCRIPTION
**Pull request by TrechNex**
Fixes #267 

Changes proposed in this pull request:
- Changes "Gimpressionist..." in menu to "Impressionist..."
- Changes Gimpressionist window title to "Impressionist"
- Changes default text to "Impressionist Defaults"

Translated into as many languages as was feasible.

### CODE REVIEW

**Comment by TrechNex** [comment]
Screenshots

**Comment by TrechNex** [comment]
@chaomodus my approach has been "if I'm not sure, leave it alone". If you're confident about making those translations feel free to add to this branch :)

(I've never been particularly good with foreign languages unfortunately. Previous PRs have mostly been about substituting proper nouns, which was much easier!)

**Comment by TrechNex** [comment]
An addendum to that would be this part of the wiki where I documented how to update translations and test them: https://wiki.glimpse-editor.org/index.php?title=Building_Glimpse#Fixing_Translations

**Comment by chaomodus** [comment]
I'll like go ahead and just add fixes to this PR if that's cool :|

**Comment by chaomodus** [comment]
More fixes incoming, but i'll batch them all as one commit.

**Comment by chaomodus** [comment]
And, done.

**Comment by TrechNex** [comment]
Can confirm those changes need to look good. For others following this PR, this is a good example of how translations are applied where they're present and default values are used when they are not:

**Pull request merged**
