### PR TITLE
[snap] Many ported updates from the snapcrafters/gimp project

### PR DESCRIPTION
**Pull request by hellsworth**
Changes proposed in this pull request:
  - Update the cflags from O2 to O3
  - Update build and runtime libraries
  - Include launcher-specific directly
  - Better organized ldcache actions

### CODE REVIEW

**Comment by hellsworth** [comment]
I built this locally, and then lightly tested it in a hirsute ubuntu vm and it all looked great.

**Comment by hellsworth** [comment]
For the three branches, dev-g210, beta-g210, and glimpse-0-2, the snapcraft.yaml is slightly different to track the different branches and such. This was how Bobby wanted it way back... So that is why there are 3 PRs.

If you would like to only keep one branch updated/published, that's fine but just tell me what you'd like to do.

**Comment by hellsworth** [comment]
could you make a branch like glimpse-0-2-snap-updates or something? I think this glimpse-0-2 branch isn't under live development since you're focusing on Glimpse NX, right? If glimpse-0-2-snap-updates exists then i can make a new PR to merge there.

**Comment by TrechNex** [comment]
To confirm, this was autoclosed when I manually merged it to glimpse-0-2. I'm back just for this weekend to tie up loose ends on this project @hellsworth.

**Pull request merged**
