### PR TITLE
POSTPONED: Add link to new Liberapay shared donation pool

### PR DESCRIPTION
**Pull request by TrechNex**
Changes proposed in this pull request:
- Adds Liberapay shared funding pool for our contributors to join

This is based on feedback we received after our decision to deprecate the Patreon account.

The role of the Open Collective will continue to be funding our project's costs using donations from the community.

The role of the Liberapay will be to provide a pool of donations that goes directly to our contributors for the time and hard work they contribute to this project. (It also provides an alternative donation method for those who do not want to use PayPal)

### CODE REVIEW

**Comment by TrechNex** [comment]
This is a proposal, and I will drop the PR/delete the Liberapay team if the feedback internally from our project is not positive.

**Comment by Member1221** [comment]
We need to check if this is allowed within the OpenCollective rules.

**Comment by TrechNex** [comment]
@Member1221 I'm not sure to which rules you prefer. Essentially this is the equivalent of us asking for individual donations, but streamlining the process with a donation pool we share.

This is not the same as Open Collective, where we would raise invoices and submit expense claims for things that have cost the project money.

**Comment by TrechNex** [comment]
However, if it turns out I'm literally the only person with a Liberapay account then the "shared pool" idea is rubbish and I'll get rid of it. But I think it would be a shame because I am not sure what mechanism we would use for people to be reimbursed for their time otherwise without agreeing to let them raise an invoice first.

**Comment by TrechNex** [comment]
After discussing on Matrix, postponing this issue until after 0.1.0 is released so we can receive feedback from our project's community before proceeding.

**Comment by TrechNex** [comment]
Linking to #101

**Comment by TrechNex** [comment]
Closing this PR to avoid confusing people. Also deleted the team, so the links are broken anyway!

**Pull request closed without merging**
