### PR TITLE
Add new splash screen, remove old garbage

### PR DESCRIPTION
**Pull request by Member1221**

### CODE REVIEW

**Comment by TreacherousNexus** [comment]
Is it possible to get rid of the other gimp images in the same data/images folder, or are they needed for the project to build?

**Comment by Member1221** [comment]
We'll need replacements for those, so no those can't be removed yet.

**Comment by Member1221** [comment]
Here's a screenshot (where i replaced the splash in GNU Image Manipulation Program)
billede

**Comment by TreacherousNexus** [comment]
This is a good start! We should avoid closing the issue until we have replacements for all branding assets :+1:

**Pull request closed without merging**
