### PR TITLE
Add AppImage package recipe

### LINKED ISSUE #108: Build and upload continuous AppImage for Linux
@TrechNex wrote in https://github.com/glimpse-editor/Glimpse/issues/99#issuecomment-524847059:

> We have so far established that Glimpse 0.1 will be a Flatpak and an AppImage on Linux. 

This ticket is about tracking the progress of AppImage packaging.

First off, as "the AppImage guy" I would like to offer my help. 

In addition, there is someone _far_ more knowledgable about compiling and packaging the upstream project of Glimpse in AppImage format: @aferrero2707. He has doing a terrific job in producing AppImages of the GNU Image Manipulation Project over the years, and has been prolific on the https://discuss.pixls.us/t/community-built-software/2137 forum. Because he is building on CentOS 7, the resulting binaries can run on pretty much all still-supported distribution versions.

Here is the repository that holds his Travis CI build scripts (using Docker):
https://github.com/aferrero2707/gimp-appimage

I think this could be used more or less 1:1 to build Glimpse AppImages, too. His AppImages have been street-tested and refined over the years, so instead of starting from scratch I'd suggest checking out his work. He has been in discussion with the GNU Image Manipulation Project about upstreaming his work, but so far it has not happened yet.

### PR DESCRIPTION
**Pull request by azubieta**
Fixes #108 

Changes proposed in this pull request:
- appimage-builder recipe
- AppImage build github workflow

### CODE REVIEW

**Comment by probonopd** [comment]
Great work @azubieta.

It would be nice if the AppImage could follow the standard naming scheme, which means "_" should replace blanks, and a version number and/or build number and/or commit sha should be part of the filename.

Thanks a lot! :+1:

**Comment by azubieta** [comment]
@probonopd what about Glimpse_Image_Editor-8.git-f7253c1-x86_64.AppImage ?

**Comment by TrechNex** [comment]
Doing a provisional merge into `dev-g210`, and I'll take it from there to tidy things up & test it. Will link next PR to this

**Comment by azubieta** [comment]
Urrah!

Please feel free to get in touch in case of issues.

**Comment by azubieta** [comment]
Oh, notice that you will have to change the lines bellow in order to enable the AppImage build job on every commit

https://github.com/glimpse-editor/Glimpse/blob/683f441863e2d211b3920d402d75a41c308fcbea/.github/workflows/build-appimage.yml#L3-L7

**Comment by TrechNex** [comment]
Indeed, I was aware of this. The dummy value there is helpful because I'm going to be have the build behaving differently depending on which branch it's operating against. 👍

**Pull request merged**
