### PR TITLE
Some changes to the version definition

### PR DESCRIPTION
**Pull request by bochecha**
*Note: This is trivial, but I found it while working on the metadata changes (PR coming soon) but it's unrelated so here it is in its own PR.*

The `configure.ac` script defines and manages **a lot** of variables. It's a complex beast.

This makes it just a tiny bit simpler by:

* removing an unnecessary intermediate variable;
* defining all version variables from the major/minor/micro versions, rather than hardcoding;

### CODE REVIEW

**Comment by TrechNex** [comment]
Please ensure you build this and test throughout the application UI that this doesn't break things. I lost many evenings to fiddling with the version variables!

**Comment by bochecha** [comment]
> Please ensure you build this and test throughout the application UI that this doesn't break things. I lost many evenings to fiddling with the version variables!

I grepped and the variable I remove isn't used anywhere in the code. It can't even be because it's not in an `AC_SUBST` call.

**Comment by TrechNex** [comment]
Is this still needed?

**Comment by bochecha** [comment]
> Is this still needed?

It never was "needed" per se. It's a trivial simplification of the build system.

The build system is overcomplicated and could use a lot of those, but this is the one I stumbled upon and figured I'd send.

**Comment by TrechNex** [comment]
Understood! I just saw this had been sat for 14 days without anything new and was checking if this was still relevant.

Once again if you can rebase with dev-g210 changes I'll approve and merge.

**Comment by bochecha** [comment]
Rebased.

**Pull request merged**
