### PR TITLE
Appimage packaging

### LINKED ISSUE #108: Build and upload continuous AppImage for Linux
@TrechNex wrote in https://github.com/glimpse-editor/Glimpse/issues/99#issuecomment-524847059:

> We have so far established that Glimpse 0.1 will be a Flatpak and an AppImage on Linux. 

This ticket is about tracking the progress of AppImage packaging.

First off, as "the AppImage guy" I would like to offer my help. 

In addition, there is someone _far_ more knowledgable about compiling and packaging the upstream project of Glimpse in AppImage format: @aferrero2707. He has doing a terrific job in producing AppImages of the GNU Image Manipulation Project over the years, and has been prolific on the https://discuss.pixls.us/t/community-built-software/2137 forum. Because he is building on CentOS 7, the resulting binaries can run on pretty much all still-supported distribution versions.

Here is the repository that holds his Travis CI build scripts (using Docker):
https://github.com/aferrero2707/gimp-appimage

I think this could be used more or less 1:1 to build Glimpse AppImages, too. His AppImages have been street-tested and refined over the years, so instead of starting from scratch I'd suggest checking out his work. He has been in discussion with the GNU Image Manipulation Project about upstreaming his work, but so far it has not happened yet.

### PR DESCRIPTION
**Pull request by TrechNex**
Fixes #108 

Changes proposed in this pull request:
- Automatically creates an AppImage for the development branch (TODO)
- Clears away Vagrant VM quick start that no longer works and won't until a good Ubuntu 20.04 LTS box is released
- Rolls back mypaint-brushes to 1.3.1
- Introduces new default configurations that should improve performance

### CODE REVIEW

**Comment by azubieta** [comment]
@TrechNex Hi! Sorry for the delay, should I take this PR as base for adding the recipe. I have some free time today to help you :)

**Comment by TrechNex** [comment]
@azubieta thanks for getting back to me. We actually produce ZIP files for every commit using our automated tooling. 

You can see the latest ones here: https://github.com/glimpse-editor/Glimpse/actions?query=branch%3Adev-g210
The 280MB file under "artefacts" here is what you're looking for: https://github.com/glimpse-editor/Glimpse/runs/790771907?check_suite_focus=true

I should point out though that it's built with the bare minimum of enabled functionality and prerequisites, as you'll see from the workflow file: https://github.com/glimpse-editor/Glimpse/actions/runs/141825189/workflow

You can find comprehensive build instructions here: https://github.com/glimpse-editor/Glimpse/wiki

**Comment by azubieta** [comment]
I have made some progress, it seems that the installation wizard has some fixed paths. Any idea on how to change it?
Screenshot_20200702_230527

**Comment by probonopd** [comment]
Maybe @aferrero2707 has seen this before and knows what needs to be done?

**Comment by aferrero2707** [comment]
@TrechNex In the GIMP AppImage case, the path to the bundled etc folder is specified at runtime via an environment variable, see here: https://github.com/aferrero2707/gimp-appimage/blob/master/AppRun.sh#L62

**Comment by TrechNex** [comment]
The changes in this PR have been superced by changes outside of it, and the changes I made here also don't particularly relate to the creation of the AppImage.

I think the comments here though are important. cc @BrainBlasted @Member1221

**Pull request closed without merging**
