### PR TITLE
Changed incorrect --extradir option to --extra-dir (gtkdoc-fixxref)

### PR DESCRIPTION
**Pull request by zoe1337**
I had build issues on [Arch linux](https://aur.archlinux.org/packages/glimpse-editor-git/#comment-755608) and one of the problems was caused by an incorrect parameter passed to gtkdoc-fixxref.

It still does not build but fails at a different libtool error I'm not smart enough to fix.

```
make --debug=all
(...)

make[3]: Entering directory '/home/zoe/.cache/yay/glimpse-editor-git/src/Glimpse/devel-docs/libglimpse'
Putting child 0x55e33b6ea730 (scan-build.stamp) PID 1040091 on the chain.
Live child 0x55e33b6ea730 (scan-build.stamp) PID 1040091 
  DOC   Scanning header files
Reaping winning child 0x55e33b6ea730 PID 1040091 
Live child 0x55e33b6ea730 (scan-build.stamp) PID 1040093 
  DOC   Introspecting gobjects
gcc: error: ../../.libs/libglimpse-2.0.so: No such file or directory
gcc: error: ../../.libs/libglimpseui-2.0.so: No such file or directory
2020-07-11 20:16:00,417:scangobj.py:execute_command:1199:WARNING:Linking scanner failed: 1, command: /bin/sh ../../libtool --tag=CC --mode=link gcc -lgobject-2.0 -lglib-2.0 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wall -Wdeclaration-after-statement -Wmissing-prototypes -Werror=missing-prototypes -Wmissing-declarations -Winit-self -Wpointer-arith -Wmissing-format-attribute -Wformat-security -Wlogical-op -Wtype-limits -fno-common -fdiagnostics-show-option -Wreturn-type -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now libglimpse-scan.lo ../../libglimpsebase/libglimpsebase-2.0.la ../../libglimpsecolor/libglimpsecolor-2.0.la ../../libglimpsemath/libglimpsemath-2.0.la ../../libglimpseconfig/libglimpseconfig-2.0.la ../../libglimpsewidgets/libglimpsewidgets-2.0.la ../../libglimpse-2.0.la ../../libglimpseui-2.0.la -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lharfbuzz -lfontconfig -lfreetype -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -o libglimpse-scan
Reaping losing child 0x55e33b6ea730 PID 1040093 
make[3]: *** [Makefile:952: scan-build.stamp] Error 1
```

### CODE REVIEW

**Comment by zoe1337** [comment]
Oh, apparently it builds in the CI system, which means something is wrong with my toolchain. But I tried on multiple machines of mine (all running latest Arch) and all of them fail. maybe libtool is too new? At least it warned me about being so.

**Comment by TrechNex** [comment]
In our CI system we use build flags to disable documentation generation, so this may turn out to be an important bugfix. We'll see if we can reproduce it when we merge into beta branch and try to do those builds

**Comment by zoe1337** [comment]
@TrechNex ping

**Comment by TrechNex** [comment]
Merging now. @zoe1337 did you want me to credit you in `authors.xml` as "zoe1337" or Zoé Bőle?

**Comment by zoe1337** [comment]
@TrechNex Zoé Bőle -- thanks!

**Pull request merged**
