### PR TITLE
modify autoconf/automake to generate `glimpse` binary

### PR DESCRIPTION
**Pull request by igalic**
we create a new variable in `configure.ac`, `GLIMPSE_APP_NAME` and insert it where ever currently `gimp-` or `gimp_` is used.

### CODE REVIEW

**Comment by igalic** [comment]
or so goes the theory… in practice, it currently doesn't work:

```
automake: error: 'bin_PROGRAMS' contains configure substitution,
automake: but 'EXTRA_PROGRAMS' not defined
app/Makefile.am:81: warning: variable '@GLIMPSE_APP_NAME@_@GLIMPSE_APP_VERSION@_SOURCES' is defined but no program or
app/Makefile.am:81: library has '@GLIMPSE_APP_NAME@_@GLIMPSE_APP_VERSION@' as canonical name (possible typo)
app/Makefile.am:231: warning: variable '@GLIMPSE_APP_NAME@_console_@GLIMPSE_APP_VERSION@_SOURCES' is defined but no program or
app/Makefile.am:231: library has '@GLIMPSE_APP_NAME@_console_@GLIMPSE_APP_VERSION@' as canonical name (possible typo)
app/Makefile.am:211: warning: variable '@GLIMPSE_APP_NAME@_@GLIMPSE_APP_VERSION@_LDADD' is defined but no program or
app/Makefile.am:211: library has '@GLIMPSE_APP_NAME@_@GLIMPSE_APP_VERSION@' as canonical name (possible typo)
app/Makefile.am:237: warning: variable '@GLIMPSE_APP_NAME@_console_@GLIMPSE_APP_VERSION@_LDADD' is defined but no program or
app/Makefile.am:237: library has '@GLIMPSE_APP_NAME@_console_@GLIMPSE_APP_VERSION@' as canonical name (possible typo)
app/Makefile.am:205: warning: variable '@GLIMPSE_APP_NAME@_@GLIMPSE_APP_VERSION@_LDFLAGS' is defined but no program or
app/Makefile.am:205: library has '@GLIMPSE_APP_NAME@_@GLIMPSE_APP_VERSION@' as canonical name (possible typo)
autoreconf: automake failed with exit status: 1
```

**Comment by TrechNex** [comment]
I learned quickly that just doing a find and replace was a bad plan as it just broke everything :sweat_smile: 

I tried to troubleshoot this but couldn't find the issue. My guess would be that there's a reason they hard-coded "gimp" in some places instead of relying on gimp_app_name. 

The actual error itself is also moaning about `EXTRA_PROGRAMS` so guessing that's triggered from somewhere important that still uses "gimp" instead of "glimpse".

**Comment by TrechNex** [comment]
Also, I'm not sure how much we need to worry about the gimp console stuff. It's a nice to have but perhaps not essential feature.

**Comment by igalic** [comment]
cc @ng-0

**Comment by TrechNex** [comment]
This was autoclosed because of the change of repository name. You can reopen it by changing the upstream branch it tracks :)

**Pull request closed without merging**
